- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Check if SSL certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: ssl_cert

- name: Configure NGINX with HTTP and HTTPS (if SSL exists)
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/sites-available/color_finder
  when: not ssl_cert.stat.exists
    
- name: Enable NGINX site
  file:
    src: /etc/nginx/sites-available/color_finder
    dest: /etc/nginx/sites-enabled/color_finder
    state: link

- name: Ensure NGINX is running
  service:
    name: nginx
    state: restarted

- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain SSL certificate
  command:
    cmd: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m {{ domain_email }}
  when: not ssl_cert.stat.exists

- name: Reload NGINX after SSL certificate generation
  service:
    name: nginx
    state: reloaded
  when: ssl_cert.stat.exists
