- name: Deploy with the Docker
  hosts: localhost
  become: true
  vars:
    ansible_become_password: '{{ ansible_become_pass }}'
  tasks:
    - name: Log in to Github Container Registry
      community.docker.docker_login:
        registry: ghcr.io
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    
    - name: Pull latest Docker image
      community.docker.docker_image:
        name: ghcr.io/lcbiplove/color_finder
        tag: latest
        source: pull
    
    - name: Stop and remove existing container
      community.docker.docker_container:
        name: color_finder
        state: absent

    - name: Run the Docker container
      community.docker.docker_container:
        name: color_finder
        image: ghcr.io/lcbiplove/color_finder:latest
        ports:
          - "8888:5000"