name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_GHCR_USER: ${{ secrets.DOCKER_GHCR_USER }}
  DOCKER_GHCR_PASS: ${{ secrets.DOCKER_GHCR_PASS }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_SERVER_USER: ${{ secrets.SSH_SERVER_USER }}
  SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
  DOMAIN_NAME_VAR: ${{ vars.DOMAIN_NAME }}
  DOMAIN_EMAIL_VAR: ${{ vars.DOMAIN_EMAIL_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: $DOCKER_GHCR_USER
          password: $DOCKER_GHCR_PASS

      - name: Build and push Docker image using Docker Compose
        run: |
          docker compose build
          docker compose push

  deploy-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up SSH for server access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: $SSH_PRIVATE_KEY

      - name: Deploy with Ansible from the server
        run: |
          ansible-playbook ansible/playbook.yml -i "$SSH_SERVER_IP," -u $SSH_SERVER_USER \
          --extra-vars "domain_name=$DOMAIN_NAME_VAR docker_username=$DOCKER_GHCR_USER docker_password=$DOCKER_GHCR_PASS domain_email=$DOMAIN_EMAIL_VAR "
