name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Github Container Registry
        run: |
          echo ${{ secrets.DOCKER_GHCR_PASS }} | docker login ghcr.io -u ${{ secrets.DOCKER_GHCR_USER }} --password-stdin
      - name: Build and push Docker image using Docker Compose
        run: |
          docker compose build
          docker compose push

  deploy-with-ansible:
    needs: build-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Prepare Ansible Related Files
        run: |
          cp docker-compose.yml ansible/roles/docker/tasks
          tar -cvf ansible.tar ansible

      - name: Copy Ansible File via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "ansible.tar"
          target: "color-finder"

      - name: Deploy with Ansible from the server using Appleboy SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf ~/color-finder/ansible
            tar -xvf ~/color-finder/ansible.tar -C ~/color-finder
            rm -rf ~/color-finder/ansible.tar
            ansible-playbook ~/color-finder/ansible/playbook.yml -i "localhost," -c local \
              -e "domain_name=${{ secrets.DOMAIN_NAME }} docker_username=${{ secrets.DOCKER_GHCR_USER }} docker_password=${{ secrets.DOCKER_GHCR_PASS }} domain_email=${{ secrets.DOMAIN_EMAIL }} ansible_become_pass=${{ secrets.ANSIBLE_BECOME_PASS }}"